"use client";

import { useState } from "react";
import DashboardShell, {
  useDashboard, DashboardTopbar, PageTitle, StatCard,
  type FKJob,
} from "@/components/DashboardShell";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

function detectN(counts: Record<string, number>): number | null {
  const keys = Object.keys(counts);
  if (!keys.length) return null;
  const len = keys[0].length;
  return keys.every(k => k.length === len && /^[01]+$/.test(k)) ? len : null;
}

/** Generate realistic-looking sample counts for n qubits (up to n=20 for display) */
function generateSample(n: number): string {
  const shots = 1000;
  const states: Record<string, number> = {};
  // Produce ~4 dominant states + noise for small n, fewer for large n
  const numStates = Math.min(8, Math.pow(2, n));
  const zeros = "0".repeat(n);
  const ones  = "1".repeat(n);
  // Always include all-zeros and all-ones as dominant
  states[zeros] = Math.round(shots * 0.45);
  if (n > 0) states[ones] = Math.round(shots * 0.45);
  let remaining = shots - (states[zeros] ?? 0) - (states[ones] ?? 0);
  // Fill a few random error states
  let filled = 2;
  while (remaining > 0 && filled < numStates) {
    const bits = Array.from({ length: n }, () => Math.random() > 0.5 ? "1" : "0").join("");
    if (!states[bits]) { const c = Math.max(1, Math.round(remaining * 0.4)); states[bits] = c; remaining -= c; filled++; }
  }
  if (remaining > 0) states[zeros] = (states[zeros] ?? 0) + remaining;
  return JSON.stringify(states, null, n <= 5 ? 2 : 0);
}

const DEVICES = [
  { group: "IBM",     items: ["ibm_marrakesh","ibm_torino","ibm_kingston"] },
  { group: "IQM",     items: ["iqm_garnet","iqm_emerald","iqm_spark"] },
  { group: "Rigetti", items: ["rigetti_cepheus","rigetti_aspen_m3"] },
];

function OverviewContent() {
  const { me, apiKey, refreshMe, addJob } = useDashboard();

  const [countsInput, setCountsInput] = useState('{"00": 480, "11": 520}');
  const [nInput, setNInput]   = useState("2");
  const [nAuto, setNAuto]     = useState(true);
  const [sampleMode, setSampleMode] = useState(false); // true when counts were generated by ⚡ ejemplo
  const [device, setDevice]   = useState("ibm_marrakesh");
  const [method, setMethod]   = useState<"rem_snn"|"rem">("rem_snn");
  const [correcting, setCorrecting] = useState(false);
  const [result, setResult]   = useState<{ corrected: Record<string,number>; latency_ms: number; method: string } | null>(null);
  const [err, setErr]         = useState<string|null>(null);
  const [jsonErr, setJsonErr] = useState<string|null>(null);

  const N_SYNC_LIMIT = 10; // API Gateway 29s timeout — noisebridge O(2^n) exceeds it above n=10

  function handleCountsChange(v: string) {
    setCountsInput(v);
    setJsonErr(null);
    setResult(null);
    setErr(null);
    setSampleMode(false); // user is editing manually
    try {
      const p = JSON.parse(v);
      if (nAuto) { const d = detectN(p); if (d) setNInput(String(d)); }
    } catch { setJsonErr("JSON inválido"); }
  }

  async function handleCorrect(e: React.FormEvent) {
    e.preventDefault();
    if (!apiKey) return;
    setErr(null); setResult(null);
    let counts: Record<string,number>;
    try { counts = JSON.parse(countsInput); } catch { setErr("JSON de counts inválido."); return; }
    const n = parseInt(nInput, 10);
    if (!Number.isFinite(n) || n < 1 || n > 127) { setErr("n debe ser 1–127."); return; }
    if (n > N_SYNC_LIMIT) {
      setErr(`n=${n} excede el límite síncrono (n≤${N_SYNC_LIMIT}). Para circuitos de alta profundidad usa la SDK directamente: pip install noisebridge`);
      return;
    }
    const keyLens = [...new Set(Object.keys(counts).map(k => k.length))];
    if (keyLens.length && !keyLens.includes(n)) {
      setErr(`n=${n} pero tus claves tienen ${keyLens[0]} bits. Pulsa "↺ auto" para corregirlo automáticamente.`); return;
    }
    setCorrecting(true);
    try {
      const res = await fetch(`${API_URL}/v1/correct`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-API-Key": apiKey },
        body: JSON.stringify({ counts, n, device, method }),
      });
      let data: Record<string,unknown> = {};
      try { data = await res.json(); } catch { /* */ }
      if (!res.ok) { setErr((data.detail as string) ?? `Error ${res.status}`); return; }
      const job = data as { corrected: Record<string,number>; latency_ms: number; method: string };
      setResult(job);
      addJob({ id: `job_${Date.now()}`, timestamp: new Date().toISOString(), device, method, n, counts, corrected: job.corrected, latency_ms: job.latency_ms });
      refreshMe();
    } catch { setErr("No se pudo contactar la API."); }
    finally { setCorrecting(false); }
  }

  const tierColor = me?.tier === "pro" ? "#a78bfa" : me?.tier === "enterprise" ? "#67e8f9" : "rgba(255,255,255,0.4)";

  return (
    <>
      <DashboardTopbar title="Overview" />
      <main className="flex-1 px-8 py-8">
        <PageTitle title="Overview" sub="Estado de tu cuenta y corrección rápida de ruido cuántico." />

        {/* Stats */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          <StatCard label="Hoy" value={me?.requests_today ?? 0}
            sub={me?.daily_limit ? `de ${me.daily_limit}` : "ilimitado"}
            iconPath="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
            iconColor="#7c3aed" iconBg="rgba(124,58,237,0.15)" />
          <StatCard label="Total" value={me?.requests_total ?? 0} sub="correcciones"
            iconPath="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
            iconColor="#06b6d4" iconBg="rgba(6,182,212,0.12)" />
          <StatCard label="Tier" value={(me?.tier ?? "Free").charAt(0).toUpperCase()+(me?.tier??"free").slice(1)}
            sub={me?.tier === "free" ? "100 req/día" : "ilimitado"}
            iconPath="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z"
            iconColor={tierColor} iconBg="rgba(124,58,237,0.12)" />
          <StatCard label="Último uso"
            value={me?.last_request_at ? new Date(me.last_request_at).toLocaleDateString("es",{day:"2-digit",month:"short"}) : "Nunca"}
            sub={me?.last_request_at ? new Date(me.last_request_at).toLocaleTimeString("es",{hour:"2-digit",minute:"2-digit"}) : "—"}
            iconPath="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
            iconColor="rgba(255,255,255,0.35)" iconBg="rgba(255,255,255,0.06)" />
        </div>

        {/* Main grid */}
        <div className="grid lg:grid-cols-5 gap-6">
          {/* Correction widget — 3 cols */}
          <div className="lg:col-span-3 rounded-2xl p-6" style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.07)" }}>
            <div className="flex items-center gap-2 mb-5">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#7c3aed" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <path d="M13 10V3L4 14h7v7l9-11h-7z"/>
              </svg>
              <h2 className="text-sm font-bold text-white">Corrección rápida</h2>
            </div>

            <form onSubmit={handleCorrect} className="space-y-4">
              <div>
                <label className="block text-[11px] font-bold text-white/35 uppercase tracking-widest mb-1.5">Counts (JSON)</label>
                <textarea value={countsInput} onChange={e => handleCountsChange(e.target.value)}
                  rows={3} spellCheck={false}
                  className="w-full px-3 py-2.5 rounded-xl text-xs font-mono text-white/80 outline-none resize-none"
                  style={{ background: "rgba(255,255,255,0.04)", border: `1px solid ${jsonErr ? "rgba(239,68,68,0.4)" : "rgba(255,255,255,0.08)"}` }} />
                {jsonErr && <p className="text-red-400 text-xs mt-1">{jsonErr}</p>}
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label className="block text-[11px] font-bold text-white/35 uppercase tracking-widest">
                      Qubits (n)
                      {nAuto && <span className="ml-1 normal-case text-violet-400/60 font-normal">· auto</span>}
                    </label>
                    <div className="flex items-center gap-2">
                      <button type="button"
                        onClick={() => { const n = Math.min(parseInt(nInput,10)||2, N_SYNC_LIMIT); setNInput(String(n)); const s = generateSample(n); setCountsInput(s); setJsonErr(null); setResult(null); setErr(null); setNAuto(false); setSampleMode(true); }}
                        className="text-[10px] text-white/30 hover:text-white/60 transition-colors font-mono">
                        ⚡ ejemplo
                      </button>
                      {!nAuto && (
                        <button type="button"
                          onClick={() => { setNAuto(true); try { const p = JSON.parse(countsInput); const d = detectN(p); if (d) setNInput(String(d)); } catch { /* */ } }}
                          className="text-[10px] text-violet-400/70 hover:text-violet-400 transition-colors font-mono">
                          ↺ auto
                        </button>
                      )}
                    </div>
                  </div>
                  <input type="number" min={1} max={127} value={nInput}
                    onChange={e => {
                      const val = e.target.value;
                      setNInput(val);
                      setNAuto(false);
                      setErr(null);
                      // If counts were generated by ⚡ ejemplo, auto-regenerate for new n
                      if (sampleMode) {
                        const nv = parseInt(val, 10);
                        if (nv >= 1 && nv <= 10) { setCountsInput(generateSample(nv)); setJsonErr(null); setResult(null); }
                      }
                    }}
                    className="w-full px-3 py-2.5 rounded-xl text-sm text-white outline-none"
                    style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }} />
                </div>
                <div>
                  <label className="block text-[11px] font-bold text-white/35 uppercase tracking-widest mb-1.5">Device</label>
                  <select value={device} onChange={e => setDevice(e.target.value)}
                    className="w-full px-3 py-2.5 rounded-xl text-sm text-white outline-none"
                    style={{ background: "rgba(20,15,40,0.98)", border: "1px solid rgba(255,255,255,0.08)" }}>
                    {DEVICES.map(({ group, items }) => (
                      <optgroup key={group} label={group}>
                        {items.map(d => <option key={d} value={d}>{d}</option>)}
                      </optgroup>
                    ))}
                  </select>
                </div>
              </div>

              {/* Method tabs */}
              <div>
                <label className="block text-[11px] font-bold text-white/35 uppercase tracking-widest mb-1.5">Método</label>
                <div className="flex gap-1.5">
                  {(["rem_snn","rem"] as const).map(m => (
                    <button key={m} type="button" onClick={() => setMethod(m)}
                      className="flex-1 py-2 rounded-lg text-xs font-semibold transition-all"
                      style={{
                        background: method===m ? "rgba(124,58,237,0.2)" : "rgba(255,255,255,0.03)",
                        border: `1px solid ${method===m ? "rgba(124,58,237,0.45)" : "rgba(255,255,255,0.07)"}`,
                        color: method===m ? "#a78bfa" : "rgba(255,255,255,0.35)",
                      }}>
                      {m}
                    </button>
                  ))}
                </div>
              </div>

              {err && (
                <div className="flex items-start gap-2 px-3 py-2.5 rounded-xl"
                  style={{ background: "rgba(239,68,68,0.07)", border: "1px solid rgba(239,68,68,0.18)" }}>
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="flex-shrink-0 mt-0.5">
                    <circle cx="7" cy="7" r="6" stroke="#f87171" strokeWidth="1.4"/>
                    <path d="M7 4.5v3M7 9.5h.01" stroke="#f87171" strokeWidth="1.4" strokeLinecap="round"/>
                  </svg>
                  <p className="text-red-400 text-xs">{err}</p>
                </div>
              )}

              <button type="submit" disabled={correcting || !!jsonErr}
                className="shimmer-btn w-full h-10 rounded-xl text-sm font-bold text-white disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center gap-2">
                {correcting ? (<><span className="w-3.5 h-3.5 rounded-full border-2 border-white/20 border-t-white animate-spin"/><span>Corrigiendo…</span></>) : "Ejecutar corrección →"}
              </button>
            </form>

            {result && (
              <div className="mt-5 rounded-xl p-4" style={{ background: "rgba(124,58,237,0.06)", border: "1px solid rgba(124,58,237,0.18)" }}>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-xs font-bold text-violet-400">Output corregido</span>
                  <span className="text-xs text-white/25 font-mono">{result.latency_ms.toFixed(1)} ms</span>
                </div>
                <div className="space-y-2">
                  {Object.entries(result.corrected).filter(([,p])=>p>0.0001).sort(([,a],[,b])=>b-a).slice(0,8).map(([state,prob])=>(
                    <div key={state} className="flex items-center gap-3">
                      <code className="text-xs font-mono text-white/45 w-20 flex-shrink-0">{state}</code>
                      <div className="flex-1 h-1 rounded-full" style={{ background: "rgba(255,255,255,0.06)" }}>
                        <div className="h-full rounded-full" style={{ width:`${(prob*100).toFixed(1)}%`, background:"linear-gradient(90deg,#7c3aed,#06b6d4)" }}/>
                      </div>
                      <span className="text-xs font-mono text-white/40 w-10 text-right flex-shrink-0">{(prob*100).toFixed(1)}%</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Right info — 2 cols */}
          <div className="lg:col-span-2 space-y-4">
            {/* Account info */}
            <div className="rounded-2xl p-5" style={{ background:"rgba(255,255,255,0.02)", border:"1px solid rgba(255,255,255,0.07)" }}>
              <h3 className="text-xs font-bold text-white/40 uppercase tracking-widest mb-4">Cuenta</h3>
              <dl className="space-y-3">
                {[
                  { l:"API Key", v: me?.key_prefix, mono:true },
                  { l:"Email",  v: me?.email ?? "—" },
                  { l:"Tier",   v: (me?.tier??"free").charAt(0).toUpperCase()+(me?.tier??"free").slice(1) },
                  { l:"Desde",  v: me?.created_at ? new Date(me.created_at).toLocaleDateString("es") : "—" },
                ].map(({l,v,mono})=>(
                  <div key={l} className="flex justify-between items-start gap-4">
                    <dt className="text-[11px] text-white/30 flex-shrink-0">{l}</dt>
                    <dd className={`text-[11px] text-right break-all ${mono?"font-mono text-white/55":"text-white/55"}`}>{v}</dd>
                  </div>
                ))}
              </dl>
            </div>

            {/* Quick start */}
            <div className="rounded-2xl overflow-hidden" style={{ border:"1px solid rgba(255,255,255,0.07)" }}>
              <div className="flex items-center gap-2 px-4 py-2.5" style={{ background:"rgba(255,255,255,0.03)", borderBottom:"1px solid rgba(255,255,255,0.06)" }}>
                <span className="text-[10px] text-white/25 font-mono uppercase tracking-widest">Quick start · Python</span>
              </div>
              <pre className="px-4 py-4 text-[11px] font-mono text-white/50 leading-relaxed overflow-x-auto"
                style={{ background:"rgba(255,255,255,0.015)" }}>
{`pip install noisebridge

from noisebridge import rem_snn_correct

corrected = rem_snn_correct(
  {"00": 480, "11": 520},
  n=2,
  device="ibm_marrakesh"
)`}
              </pre>
            </div>

            {/* Upgrade */}
            {me?.tier === "free" && (
              <div className="rounded-2xl p-5 relative overflow-hidden"
                style={{ background:"rgba(124,58,237,0.07)", border:"1px solid rgba(124,58,237,0.2)" }}>
                <div className="absolute -top-8 -right-8 w-24 h-24 rounded-full opacity-20" style={{ background:"radial-gradient(circle,#7c3aed,transparent)" }}/>
                <p className="text-sm font-bold text-white mb-0.5">Go Pro · $49/mes</p>
                <p className="text-xs text-white/35 mb-4">Requests ilimitados, todos los QPUs, soporte prioritario.</p>
                <a href="/#pricing" className="shimmer-btn inline-flex items-center justify-center w-full h-9 rounded-xl text-sm font-bold text-white">
                  Actualizar →
                </a>
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
}

export default function DashboardPage() {
  return <DashboardShell><OverviewContent /></DashboardShell>;
}
